# Kubeflow Container Build Pipeline

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg

stages:
- stage: ContainerConfig
  displayName: 'Configure and Register Containers'
  jobs:
  - job: Containers
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: 'inlineScript'
        inlineScript: '
          sudo az acr login -n $(ACR_NAME) -u $(ACR_USER_NAME) -p $(ACR_PASSWORD) && 
          cd code &&
          cd preprocess &&
          sudo docker build -t $(ACR_SERVER)/kubeflow/preprocess:$BUILD_SOURCEVERSION . &&
          sudo docker push $(ACR_SERVER)/kubeflow/preprocess:$BUILD_SOURCEVERSION '
        displayName: 'Build & Push Preprocess Image'

    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: 'inlineScript'
        inlineScript: '
          cd code &&
          cd training &&
          sudo docker build -t $(ACR_SERVER)/kubeflow/training:$BUILD_SOURCEVERSION . &&
          sudo docker push $(ACR_SERVER)/kubeflow/training:$BUILD_SOURCEVERSION '
        displayName: 'Build & Push Training Image'

    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: 'inlineScript'
        inlineScript: '
          cd code &&
          cd register &&
          sudo docker build -t $(ACR_SERVER)/kubeflow/register:$BUILD_SOURCEVERSION . &&
          sudo docker push $(ACR_SERVER)/kubeflow/register:$BUILD_SOURCEVERSION '
        displayName: 'Build & Push Register Image'


# Moved KF step to build
- stage: KubeflowTrigger
  dependsOn: ContainerConfig
  displayName: 'Trigger Kubeflow Pipeline'
  jobs:
  - job: Kubeflow
    steps:
    - task: AzureCLI@1
      env:
        KF_MAPPED_SERVICE_PRINCIPAL_PASSWORD: $(KF_SERVICE_PRINCIPAL_PASSWORD)
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials -g mlops-RG-umr -n aks-kubeflow
          kubectl port-forward --namespace kubeflow svc/ml-pipeline 8888:8888 &
          kubepid=$!
          SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          
          sudo apt-get install python3-setuptools
          pip3 install wheel
          pip3 install kfp
          
          touch script.py
          echo "import kfp" >> script.py
          echo "client = kfp.Client(host='localhost:8888')" >> script.py
          echo "client.run_pipeline('$KF_EXPERIMENT_ID', 'Run ${BUILD_BUILDID}', params={'imagetag': '${BUILD_SOURCEVERSION}', 'tenant-id': '$KF_TENANT_ID', 'service-principal-id': '$KF_SERVICE_PRINCIPAL_ID', 'service-principal-password': '$KF_MAPPED_SERVICE_PRINCIPAL_PASSWORD', 'subscription-id': '$SUBSCRIPTION_ID', 'resource-group': '$RESOURCE_GROUP', 'workspace': '$WORKSPACE_NAME', 'persistent-volume-name': '$KF_PERSISTENT_VOLUME_NAME', 'persistent-volume-path': '$KF_PERSISTENT_VOLUME_PATH', 'data-download': '$KF_DATA_DOWNLOAD', 'epochs': '$KF_EPOCHS', 'batch': '$KF_BATCH', 'learning-rate': '$KF_LEARNING_RATE', 'model-name': '$KF_MODEL_NAME'}, pipeline_id='$KF_PIPELINE_ID')" >> script.py 
          
          cat script.py
          
          python3 script.py
          
          kill $kubepid
        displayName: 'Trigger Kubeflow Pipeline'
